services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/hyttehits/index.html
      - ./styles.css:/usr/share/nginx/hyttehits/styles.css
      - ./game.js:/usr/share/nginx/hyttehits/game.js
      - ./youtube.js:/usr/share/nginx/hyttehits/youtube.js
    container_name: hitster-sjov
    restart: unless-stopped
