version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./styles.css:/usr/share/nginx/html/styles.css
      - ./game.js:/usr/share/nginx/html/game.js
      - ./youtube.js:/usr/share/nginx/html/youtube.js
      - ./README.md:/usr/share/nginx/html/README.md
    container_name: hitster-sjov
    restart: unless-stopped
